# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycut < Formula
  desc "Terminal-based video trimming TUI (ffmpeg + chafa)"
  homepage "https://github.com/emin-ozata/lazycut"
  version "0.3.7"

  depends_on "chafa"
  depends_on "ffmpeg"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.7/lazycut_0.3.7_darwin_arm64.tar.gz"
    sha256 "0349a58703c829d9051ee7e6901b7e35712a72d2760db3afffe0985c0683f76d"

    define_method(:install) do
      bin.install "lazycut"
    end
  end

  test do
    output = shell_output("#{bin}/lazycut 2>&1", 1)
    assert_match "Usage: lazycut", output
  end
end
