# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycut < Formula
  desc "Terminal-based video trimming TUI (ffmpeg + chafa)"
  homepage "https://github.com/emin-ozata/lazycut"
  version "0.3.4"

  depends_on "chafa"
  depends_on "ffmpeg"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.4/lazycut_0.3.4_darwin_amd64.tar.gz"
    sha256 "e856a0757de6ea01d649a990eb37144e2e622ba982a4e8367f587d12d96773ee"

    define_method(:install) do
      bin.install "lazycut"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/emin-ozata/lazycut/releases/download/v0.3.4/lazycut_0.3.4_darwin_arm64.tar.gz"
    sha256 "318b763f1db92f4b54ac2731e50031928d695e30071da4e7aa193e3573dba6e7"

    define_method(:install) do
      bin.install "lazycut"
    end
  end

  test do
    output = shell_output("#{bin}/lazycut 2>&1", 1)
    assert_match "Usage: lazycut", output
  end
end
